name: Commit Lint

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  commitlint:
    name: Conventional Commit lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.6.0"
      - name: Install dependencies
        run: npm ci
      - name: Lint commit message
        if: github.actor != 'dependabot[bot]' # Skip commitlint if this is a Dependabot PR
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          else
            npx commitlint --from HEAD~1 --to HEAD --verbose
          fi
