name: Commit Lint

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  commitlint:
    name: Conventional Commit lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Lint commit message
        run: npx commitlint --from origin/${{ github.event.pull_request.base.ref }} --to HEAD --verbose
