name: Allow Dependabot to Auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  run-integration-tests:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    name: Run integration tests
    # Integration tests must pass for this to run.
    uses: ./.github/workflows/integration-tests.yml

  dependabot-auto-approve:
    needs: run-integration-tests
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    name: Enable auto-approve for Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve Dependabot PRs
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  dependabot-auto-merge:
    needs: [run-integration-tests, dependabot-auto-approve]
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    name: Enable auto-merge for Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge --delete-branch "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
